In [1]:
import numpy as np 
a = np.array([7,8,9])
a

array([7, 8, 9])

In [2]:
import numpy as np 
a = np.array([7,8,9])
print(a)

[7 8 9]


In [3]:
import numpy as np
a = np.array([1,2,3,5,10])
b = np.array([0,4,5,2,7])
c = a + b
c[2]

8

In [7]:
import numpy as np
a = np.array([1,2,3,5,10])
d = a + 1
d

array([ 2,  3,  4,  6, 11])

In [8]:
import numpy as np
a = np.array([[1,2,3],[0,1,5]])
b = np.zeros([2,3], dtype=np.int16)
c = np.ones((2,3), dtype=np.int32)
d = a + b + c
print(d)

[[2 3 4]
 [1 2 6]]


In [9]:
d = np.array([(9,4,7), (7,9,8)], dtype = float) 
d

array([[9., 4., 7.],
       [7., 9., 8.]])

In [10]:
d = np.array([(9,4,7), (7,9,8)]) 
d

array([[9, 4, 7],
       [7, 9, 8]])

In [11]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [12]:
f = np.arange(10,25,3)
f

array([10, 13, 16, 19, 22])

In [13]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [14]:
e = np.full((2,2),7) 
e

array([[7, 7],
       [7, 7]])

In [15]:
np.random.random((2,2))

array([[0.96405584, 0.77786252],
       [0.45050138, 0.43723142]])

In [17]:
np.random.randint(5)

3

In [18]:
np.random.randint(10, size=(4,1))

array([[3],
       [9],
       [2],
       [2]])

In [19]:
h1.shape

NameError: name 'h1' is not defined

In [20]:
h2 = np.random.randint(5, size= 7)
h2

array([4, 0, 1, 0, 2, 4, 2])

In [21]:
h2.shape

(7,)

In [22]:
import numpy as np 
a_save = np.array([[7,8,9],[1,2,3]])
np.save('my_array', a_save)
a_load = np.load('my_array.npy')
a_load

array([[7, 8, 9],
       [1, 2, 3]])

In [23]:
print(a)
len(a)

[[1 2 3]
 [0 1 5]]


2

In [24]:
a.ndim

2

In [25]:
a.shape

(2, 3)

In [26]:
a.dtype.name

'int64'

In [27]:
a.astype(float)

array([[1., 2., 3.],
       [0., 1., 5.]])

In [28]:
import numpy as np
a = np.array([[1,2,3],[0,1,5]])
b = np.array([[4,5,7],[2,9,1]])
g = a - b 
g

array([[-3, -3, -4],
       [-2, -8,  4]])

In [29]:
np.subtract(a,b)

array([[-3, -3, -4],
       [-2, -8,  4]])

In [30]:
#print(a)
#print(b)
print(a / b)

[[0.25       0.4        0.42857143]
 [0.         0.11111111 5.        ]]


In [31]:
np.multiply(a,b)

array([[ 4, 10, 21],
       [ 0,  9,  5]])

In [32]:
np.sqrt(b).astype(int)

array([[2, 2, 2],
       [1, 3, 1]])

In [33]:
a.dot(b.T)

array([[35, 23],
       [40, 14]])

In [34]:
a.dot(b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [35]:
b.max()

9

In [36]:
b.max(axis=0)

array([4, 9, 7])

In [37]:
b.sum()

28

In [38]:
b.sum(axis=0)

array([ 6, 14,  8])

In [39]:
b.sum(axis=1)

array([16, 12])

In [40]:
k = np.array([[(9.5,4), (2,7)], [(4,7), (2,5)]], dtype = int)
k

array([[[9, 4],
        [2, 7]],

       [[4, 7],
        [2, 5]]])

In [41]:
np.sort(k)

array([[[4, 9],
        [2, 7]],

       [[4, 7],
        [2, 5]]])

In [42]:
np.sort(k,axis=2)

array([[[4, 9],
        [2, 7]],

       [[4, 7],
        [2, 5]]])

In [43]:
np.sort(k,axis=0)

array([[[4, 4],
        [2, 5]],

       [[9, 7],
        [2, 7]]])

In [44]:
b[1,2]

1

In [45]:
a[0:1]

array([[1, 2, 3]])

In [46]:
b[0:2,2]

array([7, 1])

In [47]:
b

array([[4, 5, 7],
       [2, 9, 1]])

In [48]:
b[:1]

array([[4, 5, 7]])

In [49]:
k[1,...]

array([[4, 7],
       [2, 5]])

In [50]:
b[b<6]

array([4, 5, 2, 1])

In [51]:
b.T.transpose()

array([[4, 5, 7],
       [2, 9, 1]])

In [52]:
b.ravel()

array([4, 5, 7, 2, 9, 1])

In [53]:
b.reshape(3,2)

array([[4, 5],
       [7, 2],
       [9, 1]])

In [54]:
b.reshape(3,-1)

array([[4, 5],
       [7, 2],
       [9, 1]])

In [55]:
np.append(a,b)

array([1, 2, 3, 0, 1, 5, 4, 5, 7, 2, 9, 1])

In [56]:
np.append(a,b, axis=0)

array([[1, 2, 3],
       [0, 1, 5],
       [4, 5, 7],
       [2, 9, 1]])

In [57]:
np.append(a,b, axis=1)

array([[1, 2, 3, 4, 5, 7],
       [0, 1, 5, 2, 9, 1]])

In [58]:
np.append(a,b, axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [59]:
np.insert(a, 1, 9)

array([1, 9, 2, 3, 0, 1, 5])

In [60]:
np.insert(a, 1, 9, axis=0)

array([[1, 2, 3],
       [9, 9, 9],
       [0, 1, 5]])

In [61]:
np.insert(a, 1, [5,6,7], axis=0)

array([[1, 2, 3],
       [5, 6, 7],
       [0, 1, 5]])

In [62]:
np.concatenate((a,b),axis=0)

array([[1, 2, 3],
       [0, 1, 5],
       [4, 5, 7],
       [2, 9, 1]])

In [63]:
np.vstack((a,b))

array([[1, 2, 3],
       [0, 1, 5],
       [4, 5, 7],
       [2, 9, 1]])

In [64]:
np.concatenate((a,b),axis=1)

array([[1, 2, 3, 4, 5, 7],
       [0, 1, 5, 2, 9, 1]])

In [65]:
np.hstack((a,b))

array([[1, 2, 3, 4, 5, 7],
       [0, 1, 5, 2, 9, 1]])